URL_SERVICE = "https://a3d89867-ffaa-4475-b6ae-29d562e146a0.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"